pipeline{
    agent any

    tools{
        maven 'Maven-3.6'
    }

    stages{
        stage('Build phase'){
            steps{
            sh 'java-maven-sonar-argocd-helm-k8s/spring-boot-app && mvn build'
            }
        }

    }
}